*** defines the GSPN firing rule
in PT-NORM
in GSPN

mod GSPN-EMU is
 pr STATE-TRAN-SYS .
 *** pr PT-NORM{SPTlab} . *** not used (but some operators may be used in importing modules)
 vars I O H M M' : Pbag . 
 vars N N' : Net .
 vars L L' : Tlab . *** tran. lab
 var Q Q' : Tmatrix .
 vars T T' : Tran .
 *** ordinary firing rule
 crl [firing] : N M => N fire(t(T),M) if T ; N' := N  /\ enabled(T, N M) .
endm