*** a state-transition view of (net-) rewrites 
in GSPN

fmod REWRITE is 
  pr GSPN .
  pr BAG{SPTlab} * (sort Bag{SPTlab} to RuleSet, sort NeBag{SPTlab} to NeRuleSet, op nil to nilRset) .
  var R : RuleSet .
  var M : Pbag .
  var S : System .
  sort RewGroup .
  op _-->_ : RuleSet System ->  RewGroup [ctor] .   *** a set of rewrites to the same (possibly normalized) PT system
endfm

*** trivial view

view RewGroup from TRIV to REWRITE is 
 sort Elt to RewGroup .
endv