in ALG-PN.maude

--- NOTE alternative version where transition guard are defined by strings (and are meta-parsed)
--- It seems now to be redundant, because the version where guards are representd as boolean terms with variables seems to work perfectly

--- In this version, a rewritable algebraic Petri net (REW_APN) is represented as a set of transitions, juxstaposed with a marking.
--- The REW-APN signature, which builds on the original APN definition, corresponds to module REW-ALG-PN.
--- Each transition is a 4-tuple (label, pre, post, guard) where pre and post are markings and guard is denoted by a string.
--- Transitions are terms containing variables of sort Transition, syntactically representing rewrite rules. 
--- An REW-APN term (of sort Net) is juxtaposed with a ground term of sort Marking, coming from the original definition, which represents the current state. 
--- Note that the pre-post sets of a transition are described as well by terms Marking, but these terms contain variables.
--- The REW-APN dynamics is formalized in the system module ALG-PN-EMU (emulator of a rewritable algebraic PN).
--- Transition firing is emulated by a distinguished rewrite rule that, using the meta-level representation of a specific module,
--- matches the precondition of a transition against the current marking and, if this match succeeds, 
--- adds the difference between the pre- and postcondition to the marking.
--- The predefined meta-level's metaMatch and applySubstitution are used. 
--- Transition may have guards are that are represented differently, as strings: they are evaluated using tokenize and metaParse
--- to avoid wrong 'false' evaluations (the Maude rewriting system considers variable like ground terms).
--- The guard encoding as a string has some trickness to permit the use of arbitrary variables when executing the rewrite and search commands.

--- Possible alternative (not yet implemented) : represent guards as boolean terms containing vars, like the pre-post sets of a transition; 
--- divide the modules used in guard definition into two submodules:
--- a signature, without equations, and an equational definition of operators; only use the former when meta-representing guards  

fmod REW-ALG-PN{PL :: TRIV, TL :: TRIV} is
  pr ALG-PN-MARKING{PL} .
  pr STRING .

  sorts Transition GuardedTran Net System .
  subsort Transition < GuardedTran < Net .
  
  op emptyN : -> Net [ctor] .
  op [_]_=>_ : TL$Elt Marking Marking -> Transition [ctor prec 53] .
  op _[_] : Transition String -> GuardedTran [ctor prec 57] .
  op _,_ : Net Net -> Net [ctor assoc comm id: emptyN prec 121] .
  op __ : Net Marking -> System [ctor prec 121] .
  ops pre post : GuardedTran -> Marking .
  op lab : GuardedTran -> TL$Elt .
  op guard : GuardedTran -> String .
  
  vars M M' : Marking . vars T T' : Transition .
  var N : Net . var X : TL$Elt . var P : Place . var G : String . 
  
  eq T["true"] = T .
  eq T["false"] = emptyN .
  eq pre([X] M => M') = M .
  eq post([X] M => M') = M' .
  eq lab([X] M => M') = X .
  eq guard(T) = "true" .
  eq pre(T[G]) = pre(T) .
  eq post(T[G]) = post(T) .
  eq lab(T[G]) = lab(T) .
  eq guard(T[G]) = G .
endfm

view Substitution from TRIV to META-LEVEL is
  sort Elt to Substitution .
endv

fmod SUBST-SET is
  pr SET{Substitution} * (op empty to NoSubst) .
endfm

--- finds all matches of a term in a module, returning the corresponding substitutions

fmod MATCH-FINDER is
  pr SUBST-SET .
  
  op allMatches : Module Term Term -> Set{Substitution} .
  op $allMatches : Module Term Term Nat -> Set{Substitution} .

  var mod : Module . vars T U :  Term . var X : Nat .
  var SUBST : [Substitution] .

  eq allMatches(mod, T, U) = $allMatches(mod, T, U, 0) .
  ceq $allMatches(mod, T, U, X) = SUBST, $allMatches(mod, T, U, X + 1) 
      if SUBST := metaMatch(mod, T, U, nil, X) /\ SUBST =/= noMatch .
  eq $allMatches(mod, T, U, X) = NoSubst [owise] .
endfm

--- emulates the transition firing in an algebraic net

mod ALG-PN-EMU{PL :: TRIV, TL :: TRIV} is
  pr MATCH-FINDER .
  pr LEXICAL .
  pr REW-ALG-PN{PL, TL} .
  
  op errMark : -> [Marking] [ctor] . --- used in downTerm
  op errBool : -> [Bool] [ctor] .
  ops upPre upPost upGuard : GuardedTran -> Term [memo] . --- meta representation of the preset/postset/guard of a transition
  op mod : -> Module [memo] . --- meta-representation of the module (lately bounded)
  
  var T : GuardedTran . var N : Net .
  vars M PRE POST : Marking .
  var I : Substitution .  var S : Set{Substitution} .

  eq upPre(T)   = upTerm(pre(T)) .
  eq upPost(T)  = upTerm(post(T)) .
  eq upGuard(T) = getTerm(metaParse(mod, tokenize(guard(T)), 'Bool)) .

  --- to make the match work, the right-hand side (pre) must be completed with ... ;  Mrest:Marking (alternatively the rule itself could be completed)
  --- this is because metaXmatch seems to give the same result as metaMatch (need to understand why)
  crl [firing] : N, T M => N, T (M ; POST subtr PRE) if  
        I, S := allMatches(mod, '_;_['Mrest:Marking, upPre(T)], upTerm(M)) /\ 
        (guard(T) == "true" or-else downTerm(applySubstitution(mod, upGuard(T), I), errBool) == true) /\
        PRE  := downTerm(applySubstitution(mod, upPre(T),  I), errMark) /\ 
        POST := downTerm(applySubstitution(mod, upPost(T), I), errMark)  .
        
endm

--- example: dining philosophers' algebraic nets

in PHIL-N

mod REW-DINING-PHIL is
  pr MARKING{Phil, String} .
  inc ALG-PN-EMU{String, String} .

  --- aliases for the transitions and the entire net
  op th  : Mset{Phil} Mset{Phil} Phil -> GuardedTran [memo] . 
  op pk  : Mset{Phil} Mset{Phil} Mset{Phil} Nat  ->  Transition [memo] . 
  op  e  : Mset{Phil} Mset{Phil} Mset{Phil} Nat  -> Transition [memo] . 
  op net : Mset{Phil} Mset{Phil} Mset{Phil} Phil Nat  -> Net [memo] . 
  
  eq mod = upModule('REW-DINING-PHIL, false) . --- module binding for the meta-level representation of the module
  
  var Ph : Phil . vars B B' B'' : Mset{Phil} . var X : Nat . var K : NzNat .
  
  --- transitions: th (think), pk (pick up forks), e (eat and release forks)

  eq th(B, B', Ph)  = ["th"] p("Think") |-> B Ph  ;  p("Pickup") |-> B' => p("Think") |-> B  ;  p("Pickup") |-> B' Ph
                     ["len(" + string(upTerm(B)) + ") > len(" + string(upTerm(B')) + ")"] . --- the guard len(B) > 0 means that at least two philosophers are thinking
                     
                     
  eq pk(B, B', B'', X) = ["pk"] p("Pickup") |-> B ph(X) ; p("Fork") |-> B' ph(X) ph(s(X)) ; p("Eat") |-> B''  =>  
            p("Pickup") |-> B ; p("Fork") |-> B' ; p("Eat") |-> B'' ph(X) .
  
  eq e(B, B', B'', X) = ["e"]  p("Eat") |-> B ph(X) ; p("Fork") |-> B'  ; p("Think") |-> B''  =>  
         p("Eat") |-> B ; p("Fork") |-> B' ph(X) ph(s(X)) ; p("Think") |-> B'' ph(X) .
  
  eq net(B, B', B'', Ph, X) = th(B, B', Ph) , pk(B, B', B'', X), e(B, B', B'', X) .

  op nphil : Nat -> Mset{Phil} [memo] . *** defined for convenience to set up the initial marking in a parametric way
  eq nphil(0) = empty{Phil} .
  eq nphil(K) = ph(sd(K,1)) nphil(sd(K,1)) .
  op m0 : -> Marking . 
  eq m0 =  p("Think") |-> nphil(N) ; p("Fork") |-> nphil(N) ; p("Eat") |-> empty{Phil} ; p("Pickup") |-> empty{Phil} .
  
  --- simple example of net rewrite (remove the guard of transitions)
  var T : Transition . var N : Net . var M : Marking . var G : String .
  crl N, T[G] M => N, T M if mark(M[p("Fork")]) = empty{Phil} .
endm

search in REW-DINING-PHIL : net(B:Mset{Phil}, B':Mset{Phil}, B'':Mset{Phil}, Ph:Phil, X:Nat) m0 =>! S:System .

--- debugging

--- red th(B:Mset{Phil}, B':Mset{Phil},  Ph:Phil) .

red upGuard(th(B:Mset{Phil}, B':Mset{Phil},  Ph:Phil)) . 

red allMatches(mod, '_;_['Mrest:Marking, upPre(th(B:Mset{Phil}, B':Mset{Phil},  Ph:Phil))], upTerm(m0)) . 

---variables are arbitrarily permuted/renamed (same outcome)
search in REW-DINING-PHIL : net(B':Mset{Phil}, B:Mset{Phil}, G:Mset{Phil}, Ph:Phil, J:Nat) m0 =>! S:System .