in ALG-PN.maude

--- In this version, a rewritable algebraic Petri net (REW_APN) is represented as a free comm. monoid of transitions, juxstaposed with a marking.
--- The REW-APN signature, which builds on the original APN definition, corresponds to module REW-ALG-PN.
--- Each transition is a 4-tuple (label, pre, post, guard) where pre and post are terms of sort Marking (coming from the original APN definition)
--- and the guard is a boolean term;
--- pre, post and guard may contain variables, which are instantiated when the transition is fired (pre and post describe the transition
--- input and output connection, respectively).
--- In this version, the subsort relation between transitions with a default true guard and those with a guard that is a boolean term
--- is established by a membership equation, rather than sytactically, as in the previous version.
--- Transitions syntactically encode rewrite rules. 
--- A term of sort Net (the REW-APN structure) is the AC juxtposition of transitions, and it is right juxtaposed with a ground term of sort Marking,
--- coming from the original definition, which represents the current state. 
--- As mentioned, the pre-post sets of a transition are described as well by terms of sort Marking, but these terms can contain variables.
--- The REW-APN dynamics is formalized in the system module ALG-PN-EMU (emulator of a rewritable algebraic PN).
--- Transition firing is emulated by a distinguished rewrite rule that, using the meta-level representation of a specific module,
--- matches the preset of a transition against the current marking and, if this match succeeds, 
--- adds the difference between the pre- and post-sets to the marking.
--- The predefined meta-level's metaMatch and applySubstitution are used. 
--- Transition guards are themeselves boolean terms that can contain variables.

--- NOTE the module REW-ALG-PN is parameterized by two trivial theories, for the place and for the transition labels.
--- The parameter PL is bound to the corresponding parameter of imported module ALG-PN-MARKING .



fmod REW-ALG-PN{PL :: TRIV, TL :: TRIV} is
  pr ALG-PN-MARKING{PL} .
  
  sorts DefaultTran Transition Net System .
  subsort DefaultTran < Transition < Net .
  
  op emptyN : -> Net [ctor] .
  op [_]_=>_[_] : TL$Elt Marking Marking Bool -> Transition [ctor prec 57] .
  op _,_ : Net Net -> Net [ctor assoc comm id: emptyN prec 121] .
  op __ : Net Marking -> System [ctor prec 121] .
  ops pre post : Transition -> Marking .
  op lab : Transition -> TL$Elt .
  op guard : Transition -> Bool .
  
  vars M M' : Marking . vars T T' : Transition .
  var N : Net . var L : TL$Elt . var P : Place . var G : Bool . 
  
  eq lab([L] M => M' [G])   = L .
  eq pre([L] M => M' [G])   = M .
  eq post([L] M => M' [G])  = M' .
  eq guard([L] M => M' [G]) = G .

  eq [L] M => M' [false] = emptyN .
  mb [L] M => M' [true] : DefaultTran .

endfm

view Substitution from TRIV to META-LEVEL is
  sort Elt to Substitution .
endv

fmod SUBST-SET is
  pr SET{Substitution} * (op empty to NoSubst) .
endfm

--- finds all matches of a term in a module, returning the corresponding substitutions

fmod MATCH-FINDER is
  pr SUBST-SET .
  
  op allMatches : Module Term Term -> Set{Substitution} .
  op $allMatches : Module Term Term Nat -> Set{Substitution} .

  var mod : Module . vars T U :  Term . var X : Nat .
  var SUBST : [Substitution] .

  eq allMatches(mod, T, U) = $allMatches(mod, T, U, 0) .
  ceq $allMatches(mod, T, U, X) = SUBST, $allMatches(mod, T, U, X + 1) 
      if SUBST := metaMatch(mod, T, U, nil, X) /\ SUBST =/= noMatch .
  eq $allMatches(mod, T, U, X) = NoSubst [owise] .
endfm

--- emulates the transition firing in an algebraic net

mod ALG-PN-EMU{PL :: TRIV, TL :: TRIV} is
  pr MATCH-FINDER .
  pr LEXICAL .
  pr REW-ALG-PN{PL, TL} .
  
  op errMark : -> [Marking] [ctor] . --- used in downTerm
  op errBool : -> [Bool] [ctor] .
  ops upPre upPost upGuard : Transition -> Term [memo] . --- meta representation of the preset/postset/guard of a transition
  op mod : -> Module [memo] . --- meta-representation of the module (lately bounded)
  
  var T : Transition . var N : Net .
  vars M PRE POST : Marking .
  var I : Substitution .  var S : Set{Substitution} .

  eq upPre(T)   = upTerm(pre(T)) .
  eq upPost(T)  = upTerm(post(T)) .
  eq upGuard(T) = upTerm(guard(T)) .

  --- to make the match work, the right-hand side (pre) must be completed with ... ;  Mrest:Marking (alternatively the rule itself could be completed)
  --- this is because metaXmatch seems to give the same result as metaMatch (need to understand why)
  crl [firing] : N, T M => N, T (M ; POST subtr PRE) if  
        I, S := allMatches(mod, '_;_['Mrest:Marking, upPre(T)], upTerm(M)) /\ 
        (guard(T) == true or-else downTerm(applySubstitution(mod, upGuard(T), I), errBool) == true) /\
        PRE  := downTerm(applySubstitution(mod, upPre(T),  I), errMark) /\ 
        POST := downTerm(applySubstitution(mod, upPost(T), I), errMark)  .
        
endm

--- example: dining philosophers' algebraic net

in PHIL-N

mod REW-DINING-PHIL is
  pr MARKING{Phil, String} .
  inc ALG-PN-EMU{String, String} .

  --- aliases for the transitions and the entire net
  op th  : Mset{Phil} Mset{Phil} Phil -> Transition [memo] . 
  op pk  : Mset{Phil} Mset{Phil} Mset{Phil} Nat  ->  Transition [memo] . 
  op  e  : Mset{Phil} Mset{Phil} Mset{Phil} Nat  -> Transition [memo] . 
  op net : Mset{Phil} Mset{Phil} Mset{Phil} Phil Nat  -> Net [memo] . 
  
  eq mod = upModule('REW-DINING-PHIL, false) . --- module binding for the meta-level representation of the module
  
  var Ph : Phil . vars B B' B'' : Mset{Phil} . var X : Nat . var K : NzNat .
  
  --- transitions: th (think), pk (pick up forks), e (eat and release forks)

  eq th(B, B', Ph)  = ["th"] p("Think") |-> B Ph  ;  p("Pickup") |-> B' => p("Think") |-> B  ;  p("Pickup") |-> B' Ph [true] . 
                     
  eq pk(B, B', B'', X) = ["pk"] p("Pickup") |-> B ph(X) ; p("Fork") |-> B' ph(X) ph(s(X)) ; p("Eat") |-> B''  =>  
            p("Pickup") |-> B ; p("Fork") |-> B' ; p("Eat") |-> B'' ph(X) [true] .
  
  eq e(B, B', B'', X) = ["e"]  p("Eat") |-> B ph(X) ; p("Fork") |-> B'  ; p("Think") |-> B''  =>  
         p("Eat") |-> B ; p("Fork") |-> B' ph(X) ph(s(X)) ; p("Think") |-> B'' ph(X) [true] .
  
  eq net(B, B', B'', Ph, X) = th(B, B', Ph) , pk(B, B', B'', X), e(B, B', B'', X) .

  op nphil : Nat -> Mset{Phil} [memo] . *** defined for convenience
  eq nphil(0) = empty{Phil} .
  eq nphil(K) = ph(sd(K,1)) nphil(sd(K,1)) .
  op m0 : -> Marking . 
  eq m0 =  p("Think") |-> nphil(N) ; p("Fork") |-> nphil(N) ; p("Eat") |-> empty{Phil} ; p("Pickup") |-> empty{Phil} .
  
  --- tricky example of net rewrite (set th transition's guard to a boolean term that is true if the number of philosophers in the precondition of th is greater than the number of philosophers in the precondition of pk)
  var T : DefaultTran . var T' : Transition . var N : Net . 
  vars M  M' M'' : Marking . 
  
  crl N, T M => N, T' M if lab(T) = "th" /\ len(mark(M[p("Think")])) > 1 /\
      M':Mset{Phil} := mark(pre(T)[p("Think")]) /\ M'':Mset{Phil} := mark(pre(T)[p("Pickup")]) /\ 
      T' := ["th"] pre(T) => post(T) [len(M':Mset{Phil}) > len(M'':Mset{Phil})].
endm

--- debugging

red th(B:Mset{Phil}, B':Mset{Phil},  Ph:Phil) .

red upGuard(th(B:Mset{Phil}, B':Mset{Phil},  Ph:Phil)) . 

red allMatches(mod, '_;_['Mrest:Marking, upPre(th(B:Mset{Phil}, B':Mset{Phil},  Ph:Phil))], upTerm(m0)) . 

--- arbitrary variable names can be used
search in REW-DINING-PHIL : net(B':Mset{Phil}, B:Mset{Phil}, G:Mset{Phil}, Ph:Phil, J:Nat) m0 =>! S:System .

search in REW-DINING-PHIL : net(B', B, G:Mset{Phil}, Ph, J:Nat) m0 =>* N:Net M:Marking such that N':Net, T:Transition := N:Net /\ guard(T:Transition) =/= true .