--- dining philosophers' algebraic net

in PHIL-N
in ALG-PN

mod DINING-PHIL is
  inc MARKING{Phil, String} .
  var Ph : Phil . vars B B' B'' : Mset{Phil} . var X : Nat . var K : NzNat .
  rl [th] : p("Think") |-> B Ph  ;  p("Pickup") |-> B' => p("Think") |-> B  ;  p("Pickup") |-> B' Ph .
  rl [pk] : p("Pickup") |-> B ph(X, K) ; p("Fork") |-> B' ph(X, K) ph(s(X), K) ; p("Eat") |-> B''  =>  
            p("Pickup") |-> B ; p("Fork") |-> B' ; p("Eat") |-> B'' ph(X, K) .
  rl [e] : p("Eat") |-> B ph(X, K) ; p("Fork") |-> B'  ; p("Think") |-> B''  =>  
           p("Eat") |-> B ; p("Fork") |-> B' ph(X, K) ph(s(X), K) ; p("Think") |-> B'' ph(X, K) . 
endm

--- this module defines the initial configuration of the dining philosophers' net in a parameterized way (the number of philosophers is a parameter)

fmod DINING-PHIL-MARK is 
  pr MARKING{Phil, String} .
  op nphil : NzNat -> NeMset{Phil} . *** allows creating a set of philosophers of arbitrary size
  var N : NzNat . var K : Nat . var B : Mset{Phil} .
  eq nphil(N) = $nphil(N, N, empty{Phil}) .
  op $nphil : Nat NzNat Mset{Phil} -> Mset{Phil} .
  eq $nphil(0, N, B) = B .
  eq $nphil(s(K), N, B) = $nphil(K, N, B ph(K, N)) .
  op m0 : NzNat -> Marking [memo] . 
  eq m0(N) =  p("Think") |-> nphil(N) ; p("Fork") |-> nphil(N) ; p("Eat") |-> empty{Phil} ; p("Pickup") |-> empty{Phil} .
endfm

mod DINING-PHIL-M0 is 
  inc DINING-PHIL .
  pr DINING-PHIL-MARK .
endm

search in DINING-PHIL-M0 : m0(5) =>! M:Marking . 