in shared/MAP+
in PBAG

*** flushing arc connections are represented as a map from places to set of places
fmod FLUSH-ARC{L :: TRIV} is
  pr MAP+{Place{L}, Pset{L}} * (sort Entry{Place{L},Pset{L}} to  FlushArc, sort Map{Place{L},Pset{L}} to FlushArcs,
                                  op _|->_ : Place Pset -> Entry{Place{L},Pset{L}} to _>>_ ,
                                  op emptyM to noFlushArc, op undefined to undefPset) . *** using the view Pset we import TMATRIX
  
  var F : FlushArcs . vars S S' : Pset . vars P P' : Place . var K : NzNat .
  op places : FlushArcs -> Pset .
  eq places(F) = $places(F, emptyPset) .
  op $places : FlushArcs Pset -> Pset .
  eq $places(noFlushArc, S) = S .
  eq $places(P >> S ; F, S') = $places(F, P U S U S') . 
  *** op remove : FlushArcs Pset -> FlushArcs . *** to be defined
endfm

in TMATRIX

*** extended place-adjacency representation, including marking parametric arcs 
fmod EMATRIX{L :: TRIV} is 
 pr TMATRIX{L} .
 pr FLUSH-ARC{L} .
 sort Ematrix .
 subsort Tmatrix < Ematrix .
 var Q : Tmatrix .
 var E : Ematrix .
 var F : FlushArcs .
 vars S S' : Pset .
 vars I O H B B' M : Pbag .
 vars P P' : Place .
 var K : NzNat .
 var Q' : Smatrix . *** input-output
 
 op _f:_ : Tmatrix FlushArcs -> Ematrix .
 eq Q f: noFlushArc = Q .
 op m : Ematrix -> Tmatrix .
 op f : Ematrix -> FlushArcs .
 eq m(Q f: F) = Q .
 eq m(Q) = Q .
 eq f(Q f: F) = F .
 eq f(Q) = noFlushArc .
 
 *** verifies that places are not both input and flush-in
 op well-def : Ematrix -> Bool . 
ceq well-def(Q f: F) = false if K . P + I := I(Q)  /\ $hasMapping(F, P) .
 eq well-def(Q f: F) = true [owise] .
 ***
 op enabled : FlushArcs Pbag -> Bool .
 eq enabled(noFlushArc, B) = true .
 eq enabled(P >> S ; F, K . P + B) = enabled(F, B) .
 eq enabled(F, B) = false [owise] .
 *** we double some of the operators that are in TMATRIX and map to them (for convenience)
 op enabled : Ematrix Pbag -> [Bool] . *** partial function
 ceq enabled(Q f: F, B) = enabled(Q, B) and-then enabled(F, B) if well-def(Q f: F) .
 *** test the existence of a place
 *** op in : Ematrix Place -> Bool . 
 *** eq in(Q f: F, P) = in(F, P) or-else in(Q, P) .
 *** elements of the adjacency matrix
 ops I O H : Ematrix -> Pbag .
 eq I(E) = I(m(E)) .
 eq O(E) = O(m(E)) .
 eq H(E) = H(m(E)) .
 *** set of places
 op places : Ematrix -> Pset .
 eq places(Q f: F) = places(Q) U places(F) .
 *** removes the specified places from a local matrix
 ***op remove :  Ematrix Pset -> Ematrix .
 ***eq remove(Q f: F, S) = remove(Q, S) f: remove(F, S) . 
 
 *** simulates the effect of flush arcs (assume that the transition is enabled)
  op flushInOut :  FlushArcs Pbag -> Smatrix . *** calcola l'output totale di archi flush
  eq flushInOut(F, B) = $flushInOut(F, [nilP, nilP], B) .
  op $flushInOut : FlushArcs Smatrix Pbag -> [Smatrix] . *** calcola l'output totale relativo a un posto "flush"
  eq $flushInOut(noFlushArc, Q', M) = Q' .
  eq $flushInOut(P >> S ; F , [B, B'], M +  K . P) = $flushInOut(F, [B +  K . P, B' + bagFromSet(K, S)], M) . 

 *** cumulative firing (adjacency matrix plus flush edges, assuming that the transition is enabled)
 op firing : Ematrix Pbag -> Pbag .
ceq firing(Q f: F, B) = firing(Q, B) + O(Q') - I(Q') if Q' := flushInOut(F, B) .
endfm

view Ematrix{L :: TRIV} from TRIV to EMATRIX{L} is 
  sort Elt to Ematrix . 
endv
