fmod MATCH is
  sorts Match NeMatch .
  subsort NeMatch < Match .
  op emptyMatch : -> Match .
  op _&_ : Match Match -> Match [ctor assoc comm id: emptyMatch] . 
endfm

*** this module defines classes (groups) of matches (bindings) pf the same kind, that is, potentially permutable
fmod MATCH-CLASS{X :: TRIV} is
  extending MATCH .
  sorts MatchGroup{X} MatchClass{X} .
  subsort X$Elt < MatchGroup{X}  .
  subsort MatchClass{X} < Match .
  op _,_ : MatchGroup{X} MatchGroup{X} -> MatchGroup{X} [ctor assoc comm prec  21] .
  op {_} : MatchGroup{X} -> MatchClass{X} [ctor prec 22 ] .
endfm

