*** def base, senza tutti gli operatori per gestire le etichette "strutturate" dellìapproccio modulare 
in ./shared/BAG-AND-SET
in PLACE


fmod PBAG is
 pr BAG-AND-SET{Place} * ( sort Bag{Place} to Pbag, sort NeBag{Place} to NePbag, sort ElBag{Place} to ElPbag, op nil to nilP, 
                           sort Set{Place} to Pset, sort NeSet{Place} to NePset, op emptyS to emptyPset) .
endfm


view Pbag from TRIV to PBAG is 
 sort Elt to Pbag .
endv