fmod PLACE{L :: TRIV} is
 pr NAT .
 sorts Bplace Place . 
 subsort Bplace < Place .
 var L : L$Elt . var K : NzNat .
 op p : L$Elt -> Place [ctor] .
 op p : L$Elt NzNat -> Bplace [ctor] .
 op lab : Place -> L$Elt .
 eq lab(p(L)) = L .
 eq lab(p(L,K)) = L .
 op cap : Bplace -> NzNat .
 eq cap(p(L,K)) = K .
endfm

*** default view 
view Place{X :: TRIV} from TRIV to PLACE{X} is 
 sort Elt to Place . 
endv