in PT-SYS
in SPN

*** Stochastic Petri Net plus firing rule

mod SPN-SYS is
 inc SPN .
 var M : Pbag . 
 var T : Tran .
 vars N N' : Net .
 crl [firing] : N M => N firing(T, M) if T ; N' := N  /\ enabled(T, M) /\ R:Float := firing-rate(T, M) .
endm

*** trivial view to PT-SYS (careful: same name as the view to PT-SYS)
view System from TRIV to SPN-SYS is 
 sort Elt to System .
endv

view Net from TRIV to SPN-SYS is 
  sort Elt to Net .
endv