in SPN-MC-EXE
in SPN-STATE-TRAN-SYS

mod SPN-MC-EXE-SYS is
 inc SPN-MC-EXE .
 inc SPN-STATE-TRAN-SYS .
 *** to pass from a  representation to the other
 var M  : Pbag  .
 var N  : Net .
 op toStateTran : System -> StateTranSys . *** main operator: builds the (symbolic) state-stransition view for a PT with priorities
 eq toStateTran(N M) = NET: N M: M REWM: allRewM(N M) REWN: allRewN(N M) REWS: allRewS(N M) . *** very intuitive
endm

