in PT-NET
in TLAB

*** Stochastic Petri Net signature parameterized in tran labels
fmod SPN-SIG{L :: TRIV, PL :: TRIV} is
  pr PT-NET{Tlab{L}, PL}  * (sort Set{Tlab{L}} to Set{Tlab}, sort NeSet{Tlab{L}} to NeSet{Tlab}) .
  pr CONVERSION .
  var M  : Pbag .
  var Q : Ematrix .
  var T : Tran .
  vars F F' : Float .
  var L : L$Elt . var J : Nat . var N : Net .
  *** getters
  op tag  : Tran -> L$Elt .
  op rate : Tran -> Float .
  op pol  : Tran -> Nat .
  eq tag(T) = tag(l(T)) .
  eq rate(T) = rate(l(T)) .
  eq pol(T) = pol(l(T)) .
  *** set a transition's rate
  op setRate : Tran Float -> Tran . *** change a transition's rate
  eq setRate(t(L, F, J) |-> Q, F') = t(L, F', J) |-> Q .
  op in : Net L$Elt -> Bool . *** cheks that a Net contains an action with the specified tag
 ceq in(T ; N, L) = true if tag(T) = L .
  eq in(N, L) = false [owise] .
  op firingRate : Tran Pbag -> [Float] . *** for convenience
  eq firingRate(T, M) = if pol(T) == 1 then rate(T) else rate(T) * float(if pol(T) == 0 
                           then enabDegree(I(T), M) else min(pol(T), enabDegree(I(T), M)) fi) fi .  
endfm

in PT-SYS

*** extended spn system (net + marking).
fmod SPN-SYS{L :: TRIV, PL :: TRIV} is
  pr SPN-SIG{L, PL} .
  pr PT-SYS{Tlab{L}, PL} * (sort Set{Tlab{L}} to Set{Tlab}, sort NeSet{Tlab{L}} to NeSet{Tlab}) .
endfm