*** in PTSYSTH+
in CAN-PT-SYS

mod PT-EMU{X :: PTSYSTH} is
 *** pr PT-SYS .
 pr CAN-PT-SYS .
 var T : Tran .
 var I O H S : BagP .
 var N N' : Net .
 crl [firing] : N S => N S + O - I if T |-> [I,O,H], N' := N /\ I <= S /\ H >' S .
 *** alternative 
 **** crl [firing] : (T |-> [I,O,H], N) S => (T |-> [I,O,H], N) S + O - I if I <= S /\ H >' S  .
 *** canonization version
 var C : Bool .
 crl [cfiring] : N S C => N S + O - I C if T |-> [I,O,H], N' := N /\ I <= S /\ H >' S . *** can. firing
endm