*** signature of a GSPN transition : a triple (name,prio,rate)
fmod SPT-LAB is
 pr STRING .
 pr FLOAT .
 sort Tlab .
 var W :  String .
 var R : Float .
 var P  : Nat .  
 op <<_,_,_>> : String Nat Float -> Tlab [ctor] . 
 op tag : Tlab  -> String .
 op prio : Tlab  -> Nat .
 op rate : Tlab  -> Float .
 eq tag(<< W,P,R >>) = W .
 eq prio(<< W,P,R >>) = P .
 eq rate(<< W,P,R >>) = R .

endfm

*** trivial view to a SPT-LAB
view SPTlab from TRIV to SPT-LAB is 
 sort Elt to Tlab .
endv

