*** the blockchain example (valuetools) 
in QUEUE-NODE-MOD
in SPN-NODE-MOD
in JSQ-NODE-MOD-2
in MC
in ../../modSPT/SPN-EMU-MOD.maude

*** blockchain representation (parametrized in place labels) with separated Markov-modulation 
mod MM-BLOCKCHAIN is
  inc QUEUE-NODE-SYS-MOD .
  inc SPN-NODE-SYS-MOD{String} .
  inc JSQ-NODE-SYS-MOD .
  inc MC-EMU .

  sort MMnetwork . *** markov modulated network
  op MM:_N:_ : System NetSys -> MMnetwork  [ctor] .
  op mc  : MMnetwork -> System .
  op sys : MMnetwork -> NetSys .
  var MC : System . var Sys : NetSys .
  eq mc (MM: MC N: Sys)  = MC .
  eq sys(MM: MC N: Sys) = Sys . 
endm

*** introduces algebraic compositional operators for convenience (places are indexed by labels such as "a" 3)
*** forse alcuni operatori si potrebbero spostare
mod BLOCKCHAIN-OP is
  inc MM-BLOCKCHAIN .
  var q : ElQueue . var Q : Queue . var K : NzNat . vars P P' : Place . 
  var R : Float . vars i j : Nat . var s : String . var L : Lab .
  var J : Jsq .  vars N N' : Network . var Nd : Node . var S : Pset . vars M Inh : Pbag .

  op allClients : Network Pbag -> [Nat] .
  op $allClients : Network Pbag Nat -> [Nat] .
  eq allClients(N, M) = $allClients(N, M , 0) .
  eq $allClients(emptyNetW, M, j) = j . 
  eq $allClients((Q, N), M, j) = $allClients(N, M, j + clients(Q, M)) .
  eq $allClients((Nd, N), M, j) = $allClients(N, M, j) [owise] .
  
  *** creates elementary input/output transitions (of type 1-server) to/from a given place
  ops newTin newTout : Place Float -> Tran . 
  eq newTin (P, R) = t("in", R, 1) |-> [nilP, 1 . P] .
  eq newTout(P, R) = t("out", R, 1) |-> [1 . P, nilP] . 
  *** creates a pool of similar elementary nets working in parallel 
  op pool : Queue NzNat String -> Network .  
  eq pool(Q, K, s) = repl&share(Q, K, s, pout(Q)) .
 *** connect a JSQ to a network of queues (nice!)
 op connect : Jsq Network -> Jsq .
 eq connect(J, emptyNetW) = J .
 eq connect(P |> S, (Q, N)) = connect(P |> S U pin(Q), N) .
 eq connect(J, (Nd, N)) = connect(J, N) [owise] .
 *** connect and link 
 op connect&link : Jsq Network -> Network .
 eq connect&link(J, N) = connect(J, N), N .
 *** disconnect a JSQ from network of queues (nice!)
 op disconnect : Jsq Network -> Jsq .
 eq disconnect(J, emptyNetW) = J .
 eq disconnect(P |> S, (Q, N)) = disconnect(P |> delete(pin(Q), S), N) . 
 eq disconnect(J, (Nd, N)) = disconnect(J, N) [owise] .
 *** disconnect and (re-)link 
 op disconnect&link : Jsq Network -> Network .
 eq disconnect&link(J, N) = disconnect(J, N), N .
endm

*** model using LAB as place labels
mod BLOCKCHAIN-EXE is
  inc BLOCKCHAIN-OP .
  var i : Nat . vars k k' k'' : NzNat . vars P P' : Place . var R : Float . 
  *** the modulating MC (with its initial state)
  op mmc : -> Q .
  op L : Nat -> Place . *** alias for the MC states
  op s-tran : -> Place .
  eq L(i) = p(< "mc" ; i >) . *** states of the MC 
  eq s-tran = p(< "s-tran" ; 0 >) .
  eq mmc = 1.0 |-> [1 . L(0); 1 . L(1) + 1 . s-tran ; 1 . s-tran] ; 2.0 |-> [1 . L(1); 1 . L(0) + 1 . s-tran ; 1 . s-tran] ; 
            2.0 |-> [1 . L(2); 1 . L(1) + 1 . s-tran ; 1 . s-tran] ; 1.0 |-> [1 . L(1); 1 . L(2) + 1 . s-tran ; 1 . s-tran] ;
            2.0 |-> [1 . L(2); 1 . L(3) + 1 . s-tran ; 1 . s-tran] ; 1.0 |-> [1 . L(3); 1 . L(2) + 1 . s-tran ; 1 . s-tran]  . *** RIVEDERE
  

  *** model's parameter(s) 
  op N : -> NzNat [memo] . *** timeout parameter (place capacity)
  eq N = 4 .  
  *** places defined in a parametric way
  ops emptyp pin cpuIn cpuOut gpuIn gpuOut netOut a b : NzNat -> Place [memo] .
  eq emptyp(k) = p(emptyLab, k) . *** bounded place with empty lab 
  eq pin(k)    = replica(emptyp(k), 1, "in") . *** bounded input place (symmetric style)
  eq cpuIn(k)  = replica(emptyp(k), 1, "cpu")  . 
  eq cpuOut(k) = replica(emptyp(k), 1, "cpu-Out") .
  eq gpuIn(k)  = replica(emptyp(k), 1, "gpu") .
  eq gpuOut(k) = replica(emptyp(k), 1, "gpu-Out") .
  eq netOut(k) = replica(emptyp(k), 1, "nt-Out") .
  eq a(k)      = replica(emptyp(k), 1, "a") .
  eq b(k)      = replica(emptyp(k), 1, "b") .
  op tin : -> Tran [memo] .
  eq tin  = newTin(pin(1), 2.0) . *** used in all configurations but L0
  
  
  *** the buffer component (plus the input t)
  op buffer : -> Net  [memo] .
  eq buffer = newTin(pin(N), 2.0) ; t("collect", 1.0, 1)  |-> [N . pin(N), N . p(< "b" ; 0 >, N)] ;
            t("timeout", 0.2, 1)  |-> [nilP, nilP] f: pin(N) >> p(< "b" ; 0 >, N) ;
            t("continue", 1.0, 1) |-> [nilP, nilP] f: p(< "b" ; 0 >, N) >> cpuIn(N) .      *** all'inizio non in JSQ (cambiare)     
  
  ***cpu pools
  ops cpu gpu : NzNat NzNat -> Network [memo] . *** 1st par: n. replica, 2nd: capacity of the output place 
  op singlegpu : -> Queue [memo] .
  eq cpu(k, k') = pool(newElQueue(emptyp(N), cpuOut(k'), 5.0),  k, "cpu") .
  eq gpu(k, k') = pool(newElQueue(emptyp(N), gpuOut(k'), 20.0), k, "gpu") .
  eq singlegpu = newElQueue(cpuOut(N), gpuOut(1), 20.0) . *** giusto?

 *** NETWORK
  ops A B : Place NzNat -> ElQueue [memo] . *** parametric in the input place and in the capacity of the output
  eq A(P, k) = newElQueue(P, netOut(k), 2.0) . 
  eq B(P, k) = newElQueue(P, netOut(k), 4.0) .
  op A+B : -> Network .
  eq A+B = A(p(< "a" ; 0 >, N), N), B(p(< "b" ; 0 >, N), N) .
  
  *** Storage
  op storage : -> ElQueue [memo] .
  eq storage = newElQueue(p(< "St" ; 0 >, N), p(< "St-O" ; 0 >, N), 0.2) .

  *** the network (blockchain) in the state L0
  op networksys0 : -> NetSys .
  op network  : Nat -> [Network]  [memo] .
  eq network(0) = buffer, cpu(1, N), A(cpuOut(N), N), newTout(netOut(N), 1.0) .
  eq network(1) = tin, connect&link(newJsq(pin(1)), cpu(3, N)), B(cpuOut(N), N), newTout(netOut(N), 1.0) .
  eq network(2) = tin, connect&link(newJsq(pin(1)), cpu(6, N)), singlegpu, connect&link(newJsq(gpuOut(1)), A+B), newTout(netOut(N), 1.0) . *** completare  

  eq networksys0 = network(0) : nilP . *** initial configuration
  
  var MC : System . var Q : Q . var S : Pbag . var Nw : Network . var B : Pbag .   
  *** rewrites governed by mmc -- NOTE: istantaneous w.r.t. mc change state
  crl  [S0>S1] : MM: Q S N: (Nw : B) => MM: Q 1 . L(1) N: normalize((network(1) : B)) 
         if S == 1 . L(1) + 1 . s-tran /\ in(Nw, buffer) . 
  
  crl  [S1>S0] : MM: Q S N: (Nw : B) => MM: Q 1 . L(0) N: normalize((network(0) : set(B, pin(cpu(1, N)), i))) 
          if S == 1 . L(0) + 1 . s-tran  /\ in(Nw, cpu(3, N)) /\ i := allClients(cpu(3, N), B) /\ (i <= cap(pin(cpu(1, N)))) =/= false .

  crl  [S1>S2] : MM: Q S N: (Nw : B) => MM: Q 1 . L(2) N: normalize((network(2) : B)) 
          if S == 1 . L(2) + 1 . s-tran  /\ in(Nw, cpu(3, N))  .

  crl  [S2>S1] : MM: Q S N: (Nw : B) => MM: Q 1 . L(1) N: normalize((network(1) : set(B, pin(cpu(1, N)), i))) 
          if S == 1 . L(1) + 1 . s-tran  /\ in(Nw, cpu(6, N)) /\ i := allClients(cpu(6, N), B) /\ (i <= cap(pin(cpu(1, N)))) =/= false .


  *** MM network initial configuration (for searches)
  op MMsys0 : -> MMnetwork .
  eq MMsys0 = MM: mmc 1 . L(0) N: networksys0 .  

  *** test normalizzazione
  ops network'  : -> Network .
  eq network' = tin, connect&link(newJsq(pin(1)), cpu(6, N)) .
endm