in ../JSQ
in ../../modPT/PSET-MOD

*** JSQ switcher (modular version)
fmod JSQ-MOD is
  pr JSQ{Plab} .
  pr PSET-MOD . *** set of places defined as monoid
  var var P  : Bplace  . var S : Pset . var L : Lab . var NeL : NeLab . 
  var I  : Nat . var WL : List{String} .  
  *** modularity ops  
  op replaceWithJsq : Jsq NeLab Nat -> Jsq . 
  eq replaceWithJsq(P |> S, NeL, I) = replaceWithP(P, NeL, I) |> replaceWith(S, NeL, I)  . 
  op addLabJsq : Jsq Lab Pset -> Jsq . 
  eq addLabJsq(P |> S, L, S) = addLabP(P, L, S) |> addLab(S, L, S) .
  op placesJsq : Jsq List{String} -> Pset .
  eq placesJsq(P |> S, WL) = places(S U P, WL) .
  op placesJsq : Jsq NeLab -> Pset .
  eq placesJsq(P |> S, NeL) = places(S U P, NeL) .
  op placesJsq : Jsq  -> Pset .
  eq placesJsq(P |> S) = S U P .
endfm