in ../QUEUE
in ../../modPT/MO-NET-OP

fmod SERVER-LIST-LAB is 
   protecting SERVER-LIST{Plab} .
   protecting PSET-MOD .
   vars P : Place . var F : Float . var J  : Nat . var S : Pset .
   var L : Lab . var NeL : NeLab . var WL : List{String} . 
   op replaceWithServer : Server NeLab Nat -> Server .
   eq replaceWithServer(P @ F, NeL, J) = replaceWithP(P, NeL, J) @ F .
   op addLabServer : Server Lab Pset -> Server . 
   eq addLabServer(P @ F, L, S) = addLabP(P, L, S) @ F .
   op placesServer : Server List{String} -> Pset .
   eq placesServer(P @ F, WL) = placesP(P, WL) .
   op placesServer : Server NeLab -> Pset .
   eq placesServer(P @ F, NeL) = placesP(P, NeL) .
   op placesServer : Server -> Pset .
   eq placesServer(P @ F) = P .
endfm 

view SERVER-LIST-LAB from MO-NET to SERVER-LIST-LAB is
  sort Elt to ServerList .
  sort El to Server .
  op nil to nilSeL  .
  op _;_ to __ .
  op replaceWithEl to replaceWithServer . 
  op addLabEl to addLabServer .
  op placesEl to placesServer .
endv

*** SERVER-LIST with structured label wrapped as a modular monoid with suitable compositional and normalization operators
fmod SERVER-LIST-MOD is
 pr MO-NET-OP{SERVER-LIST-LAB} .
endfm

fmod QUEUE-MOD is
  protecting QUEUE{Plab} . 
  protecting SERVER-LIST-MOD .
  var J  : Nat . var S : Pset . var L : Lab . var NeL : NeLab . var WL : List{String} .  
  var NeLS : NeServerList . vars P : Place .
  *** modular ops
  op replaceWithQueue : Queue NeLab Nat -> Queue . 
  eq replaceWithQueue(NeLS > P, NeL, J) = replaceWith(NeLS, NeL, J) >  replaceWithP(P, NeL, J) . 
  op addLabQueue : Queue Lab Pset -> Queue . 
  eq addLabQueue(NeLS > P, L, S) = addLab(NeLS, L, S) > addLabP(P, L, S)   .
  op placesQueue : Queue List{String} -> Pset .
  eq placesQueue(NeLS > P, WL) = places(NeLS, WL) U placesP(P, WL) .
  op placesQueue : Queue NeLab -> Pset .
  eq placesQueue(NeLS > P, NeL) = places(NeLS, NeL) U placesP(P, NeL) .
  op placesQueue : Queue  -> Pset .
  eq placesQueue(NeLS > P) = places(NeLS) U P .
endfm