in PSET-LAB
in MO-NET-OP
view PSET-LAB from MO-NET to PSET-LAB is
  sort Elt to Pset .
  sort El to Place .
  op nil to emptyPset  .
  op _;_ to _U_ .
  op replaceWithEl to replaceWithP . 
  op addLabEl to addLabP .
  op placesEl to placesP .
  op inEl to inP .
endv

*** new! defined as a monoid in turn set of places with structured labels used in compositional operations
fmod PSET-MOD is
   pr MO-NET-OP{PSET-LAB} .
endfm 