in JSQ
in NETWORK

*** MQN as nodes of a network
fmod JSQ-NODE{PL :: TRIV} is
  extending NETWORK{S-Pbag{PL}} .
  protecting JSQ{PL} .
  subsort Jsq < Node .
endfm

mod JSQ-NODE-SYS{PL :: TRIV} is
   including JSQ-NODE{PL} .
   var N : Network . var B : Pbag . var P : Bplace . var P' : Place  . var S : Pset . var NeS : NePset .
   op jsqRate : Jsq Pbag -> Float .
   eq jsqRate(J:Jsq, B) = 100.0 . *** dummy implementation 
   crl (N , P |> NeS) : 1 . P + B => (N , P |> NeS) : B + 1 . P' if P' U S := emin(B, NeS) /\ rate:Float := jsqRate(P |> NeS, B) .
endm
