in ../../shared/MSET
in ../../shared/PAIR
in ../../SPN
in ../ALG-PN


--- tag of net-token transition, built of a parametric tag followed by a multiset of strings representing a channel
fmod TAG{L :: TRIV} is
  protecting PAIR{L, Mset{String}} * (sort Pair{L, Mset{String}} to Tag, op <_;_> to _@_) .
endfm

view Tag{L :: TRIV} from TRIV to TAG{L} is 
 sort Elt to Tag .
endv

--- signature of stochastic net-tokens (derived from that of SPN)
fmod NT-SIG{L :: TRIV, PL :: TRIV} is
  pr SPN-SIG{Tag{L}, PL} .
  
  var TL : Tlab . var T  : Tran .   var N  : Net .
  var PB : Pbag . var S  : String . var MS : Mset{String} .

  op hasInhibitor : Net -> Bool .
  eq hasInhibitor(N ; TL |-> [I:Pbag,O:Pbag,H:NePbag]) = true .
  eq hasInhibitor(N) = false [owise] . 
  op pre : Net -> Pbag . *** cumulative pre-set
  eq pre(N) = $pre(N, nilP) .
  op $pre : Net Pbag -> Pbag .
  eq $pre(emptyNet, PB) = PB .
  eq $pre(T ; N, PB) = $pre(N, PB + I(T)) . 
  op post : Net -> Pbag . *** cumulative post-set
  eq post(N) = $post(N, nilP) .
  op $post : Net Pbag -> Pbag .
  eq $post(emptyNet, PB) = PB .
  eq $post(T ; N, PB) = $post(N, PB + O(T)) .
  op ch : Net -> Mset{String} .
  eq ch(N) = $ch(N, empty{String}) .
  op $ch : Net Mset{String} -> Mset{String} .
  eq $ch(emptyNet, MS) = MS .
  eq $ch(T ; N, MS) = $ch(N, ch(lab(T)) MS) .
  --- op ch : Tran  -> Mset{String} .  --- allows for multiple channels per transition
  --- eq ch(T) = ch(lab(T)) .
  op ch : Tlab ->  Mset{String} .
  eq ch(TL) = 2nd(tag(TL)) .
endfm


--- compact net-token marking description (multiset of markings) parametric in place labels
fmod NT-MARKING{PL :: TRIV} is
   pr MSET{Pbag{PL}} * (sort Mset{Pbag{PL}} to Mset{Pbag}, sort NeMset{Pbag{PL}} to NeMset{Pbag},
                        op empty{Pbag{PL}} to empty{Pbag}) .
                        
endfm 

--- net-token representation with compact state (markings) description parametric in node labels 
fmod NET-TOKEN{L :: TRIV, PL :: TRIV} is 
  pr (NT-MARKING{PL} + NT-SIG{L, PL} + P-MSET-BAG{PL}) * (sort Place to NtPlace, sort Bplace to NtBplace, op p to P,
                                        sort Pset to NtPset, sort NePset to NeNtPset)  . 
      --- necessary to avoid name clashes with the system net's places (we should use NtP instead of P)
      --- we should also rename Pbag to NtPbag, etc, but this is not strictly necessary
  sort NetToken .
  var N : Net .
  var B : Mset{Pbag} . *** nested multiset of markings
  vars M M' : Pbag .
  op __ : Net Mset{Pbag} -> [NetToken] [ctor] .
  op n : NetToken -> Net .
  op m : NetToken -> Mset{Pbag} .
  cmb N B : NetToken if hasInhibitor(N) = false . *** net-tokens do not have inhibitor arcs
  eq n(N B) = N .
  eq m(N B) = B .
  op cum : Mset{Pbag} -> Pbag . *** cumulative marking
  eq cum(B) = $cum(B, nilP) .
  op $cum : Mset{Pbag} Pbag -> Pbag .
  eq $cum(empty{Pbag}, M) = M .
  eq $cum(B M', M) = $cum(B, M + M') .
  op cum : NetToken -> Pbag .
  eq cum(N B) = cum(B) .
endfm


--- net-token including the object-autonomous firing rule
mod NET-TOKEN-SYS{L :: TRIV, PL :: TRIV} is
 inc NET-TOKEN{L, PL} .
 var N  : Net .
 var B  : Mset{Pbag} . 
 var M  : Pbag .
 var T  : Tran .
 crl [firing] : (T ; N) B M => (T ; N) B firing(T, M) if ch(T) = empty{String} /\ I(T) <= M /\ R:Float := firingRate(T, M) .
endm

view NetToken{L :: TRIV, PL :: TRIV} from TRIV to NET-TOKEN-SYS{L, PL} is
  sort Elt to NetToken .
endv


--- theory for synchronization of system-net transitions with net-tokens' transitions
--- a system net transition may be associated with a channel (multiset string) and it synchronizes with all net-tokens' transitions that match that channel
--- trivial encoding: a system net transition is represented by the label of corresponding rewrite rule
fth SYNCH is
  inc MSET{String} .
  op synch : String -> Mset{String} . 
endfth


--- definition of an eHornet marking parametric vs the net-tokens' and system net's place labels
--- net-tokems may be of any type and parametric in turn in node labels
mod EHORNET{L :: TRIV, PL :: TRIV, PL' :: TRIV, SY :: SYNCH} is
   generated-by MARKING{NetToken{L, PL}, PL'} * (sort Mset{NetToken{L, PL}} to Mset{NetToken}, 
                            sort NeMset{NetToken{L, PL}} to NeMset{NetToken},
                            sort  Pmarking{NetToken{L, PL}} to  Pmarking{NetToken},
                            op empty{NetToken{L, PL}} to empty{NetToken}) .
   
   var N : Net .
   vars B B' : Mset{Pbag} . *** compact net-token markings' representation
   eq (N B) (N B') = N (B B') . 
   eq (N empty{Pbag}) = empty{NetToken} .
endm
